### ISSUE TITLE
个人觉得，图片类资源文件可用.xcassets来管理较为方便。

### ISSUE THREAD

**Issue by deanxxia** [Finb/V2ex-Swift#1]
rt

**Comment by Finb** [comment]
感谢建议

一开始考虑到多配色时可能需要不同的图片资源，所以想用 bundle 管理。
不过现在配色使用tintColor后，就没必要用bundle了。。xcassets可能会更好
之后会将图片资源处理一下，

再次感谢你的建议，大兄弟~
