### ISSUE TITLE
发现一个崩溃的bug

### ISSUE THREAD

**Issue by isweal** [Finb/V2ex-Swift#12]
<img width="312" alt="2016-03-18 15 26 48" src="https://cloud.githubusercontent.com/assets/6571652/13871308/0c3927fa-ed1e-11e5-8d05-635a1928e201.png">
在Google节点点这个帖子，真机进去之后就崩了。
这是模拟器下的截图
<img width="260" alt="2016-03-18 15 32 02" src="https://cloud.githubusercontent.com/assets/6571652/13871449/9a27ef24-ed1e-11e5-882f-fd713ca0bf3d.png">
800多内存哟。

**Comment by Finb** [comment]
收到，感谢反馈！

Crash原因是评论中有个超级大的GIF图片
评论显示使用了YYText，它解析GIF时占用了大量内存。暂时只能向这个库的作者反馈一下
我先找个办法禁止解析超大GIF吧。。

其实经测试就算很大的GIF也能抗住，但这个帖子里的GIF实在是太大了 - -。

人生二十五年 notifications@github.com于2016年3月18日周五 下午3:34写道：

**Comment by Finb** [comment]
可能修复了 937c365e0cc37a8cbdbd14756a127ea7c0fab19d
