### ISSUE TITLE
如何发帖，回复，签到

### ISSUE THREAD

**Issue by hellokaton** [Finb/V2ex-Swift#14]

**Comment by Finb** [comment]
发帖暂时不可以。
回复在帖子右上角，或者点某条评论

**Comment by Finb** [comment]
签到是自动的，每天打开一次APP就可以，签到成功后会有提示

**Comment by atjiu** [comment]
大大，发帖我觉得还是有必要的，能否加一个呢？
当用手机逛v2的时候，想发个帖子，手机网页也没给链接，如果在浏览器上手动输入发帖链接，打开的页面还是pc版的，相当的不方便，所以希望能加一个这功能

**Comment by Finb** [comment]
@tomoya92 
想把发帖功能做的体验好需要点工作量，一直是想写的，不过这个项目现在只简单维护了，最近都暂时没有计划填这个坑，以后写完了通知dalao你
