### ISSUE TITLE
评论内容中有图片的时候怎么显示有什么好的想法吗？

### ISSUE THREAD

**Issue by EkkoG** [Finb/V2ex-Swift#2]
:)

**Comment by Finb** [comment]
有的，现在有两个方案，不知道哪个好，
1. 图文混排，优点是最好的还原了回复，缺点是像混排这种 ，计算量太大了，滑动出现时，可能会掉帧（后期我的要求是 整个APP要保证很高的流畅度）
   不过还是会先试试的，项目中有YYText 正好支持图文混排。
2. 像微博那样，将回复中的图片单独提取出来。然后放在指定的位置显示 ，像微博推特那样排列

到时候两种方式都会实现看看实际哪种效果更好，不过我现在比较倾向第二种

**Comment by moorlop** [comment]
iPhone6s Plus 滑动已经有点掉帧了

**Comment by EkkoG** [comment]
我用图文混排实现出来一个，不过很简陋，计算量还好，就是每张图片加载完成后要刷新整个 TableView，高度最后会缓存。
第二种和网页版差别就大了吧，有些长的回复，中间的图片是和上下文相关的，放到最后的话有点怪。

**Comment by EkkoG** [comment]
https://github.com/jverkoey/nimbus/tree/master/src/attributedlabel/src 这个控件也是支持图文混排的，不过是本地图片，如果要异步加载图片再显示还是要处理一下。

**Comment by moorlop** [comment]
图文混排就小图就OK了
想看大图点开

**Comment by Finb** [comment]
@moorlop 是的，现在掉帧很严重，因为有太多的像layer圆角之类的 。之后会处理掉这些的，

**Comment by moorlop** [comment]
还有两边侧边拉伸字体大小会变， 最好不要这样吧

**Comment by Finb** [comment]
@cielpy  嗯，看了一下 ~ 感谢 ！！

**Comment by moorlop** [comment]
在iPhone6s Plus上面 微博内容滚动要比微信朋友圈的信息滚动好多了
不知道微信和sina微博有什么区别

**Comment by Finb** [comment]
@moorlop 这些会再改的，现在UI和配色还是随便写的，我想先把大概的功能写完先

微博应该是异步绘制的吧，快速滑动时可以看到有的cell没有绘制
