### ISSUE TITLE
iOS10上运行有bug

### ISSUE THREAD

**Issue by kaixinsoft** [Finb/V2ex-Swift#32]
打开app，随便点一个主题，然后进入帖子的明细。这个时候，leftbutton和rightbutton图标变的斑白。
返回住界面，leftbutton和rightbutton的图标一直斑白，但是点击可以响应。

**Comment by Finb** [comment]
感谢反馈，
正在提交加急审核

**Comment by Finb** [comment]
已修复 807fda2f940bffcb5889df8932dda5ad4da7cf9e
