### ISSUE TITLE
显示不了内容

### ISSUE THREAD

**Issue by asasdasasd** [Finb/V2ex-Swift#36]
xcode8.1，clone下来pod install运行界面空白，提示-canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

**Comment by Finb** [comment]
建议将cocoapods 升级到最新版（1.2.0 beta3)
如果你只是想运行的话，我这里给你上传了一份已经 install 好了所有依赖库的压缩包，解压打开运行即可
https://pan.baidu.com/s/1geATmCj

**Comment by asasdasasd** [comment]
好吧，是我表述不清，是运行之后没信息
![simulator screen shot 2016 12 30 4 39 22](https://cloud.githubusercontent.com/assets/14845282/21561940/a556ba52-ceae-11e6-90e6-b7548f841502.png)

**Comment by Finb** [comment]
我这里测试 ，从github clone下来后运行是正常显示的，你这种情况估计是没请求到数据吧
