### ISSUE TITLE
验证码登陆

### ISSUE THREAD

**Issue by CoterJiesen** [Finb/V2ex-Swift#38]
怎么实现带验证码的登陆呢

**Comment by Finb** [comment]
v站登录需要验证码么？

**Comment by CoterJiesen** [comment]
不是呀  就是想请教一下 怎么才能实现带验证码的登陆  有些网站有验证码  大神们有没有相关的例子呀

**Comment by Finb** [comment]
@CoterJiesen 
每个网站都可能不一样，总结一下就是 模拟。
web浏览器也是个客户端，你要做的事基本就是模拟和浏览器一样的行为。

一般来讲 就是把 验证码图片地址（或其他什么稀奇古怪的验证码，有可能是滑动的，有可能是一些语言，这些都要你自己去模拟展示给用户）找出来展示给用户，然后让用户填写，然后你再把包含验证码的参数按照和浏览器一样的行为 提交给服务器。

如果你觉得不太懂，我建议你可以先学习一下HTTP协议。

这个issue先关了哈~ 继续交流的话可以给我发邮件。
