### ISSUE TITLE
V2EXColor.swift 里面每次都创建color， 不占内存吗

### ISSUE THREAD

**Issue by song-react** [Finb/V2ex-Swift#40]
尝试做一下缓存啊

**Comment by Finb** [comment]
肯定是不占内存的，因为用的比较少。就算实例化1W个，估计也占不了1MB的内存
另外这个对象实例化是非常快的，他包含一些颜色信息，但是并没有计算
所以这个东西直接用就行了，为这点性能我觉得没必要优化的

**Comment by song-react** [comment]
不止吧，还有alloc啊 这些东西

不如创建一个黑色一个白色的字典

**Comment by Finb** [comment]
@DingSoung 嗯，肯定是有一点点性能损耗的，但是真的没什么影响
字典倒是不用，颜色是个单例对象，所以可以用个字段保存下就行。
