### ISSUE TITLE
/.../V2ex-Swift-master/View/TopicDetailCommentCell.swift:10:8: No such module 'YYText'

### ISSUE THREAD

**Issue by jacoblee53** [Finb/V2ex-Swift#41]
已经运行了`pod install`

---
![pic2](http://oppnkay27.bkt.clouddn.com/20170809150229374042557.png)
---
![pic](http://oppnkay27.bkt.clouddn.com/20170809150229360979182.png)

**Comment by jacoblee53** [comment]
![3](http://oppnkay27.bkt.clouddn.com/20170809150229412590558.png)

**Comment by Finb** [comment]
兄弟，打开的是V2ex-Swift.xcworkspace嘛？
xcode版本多少？

**Comment by jacoblee53** [comment]
@Finb 呀！我贼鸡儿傻！
谢谢你，问题解决了！

**Comment by Finb** [comment]
😄

**Comment by jacoblee53** [comment]
![4](http://oppnkay27.bkt.clouddn.com/20170810150229487219287.png)

**Comment by Finb** [comment]
暂时还不支持swift4和xcode9。 等我兼容后再这@你。如果你现在要运行的话，需要xcode8

**Comment by jacoblee53** [comment]
多谢！但是我是swift3 xcode8
![5](http://oppnkay27.bkt.clouddn.com/20170810150229525099082.png)
![6](http://oppnkay27.bkt.clouddn.com/20170810150229528253591.png)

**Comment by jacoblee53** [comment]
还是无法运行

**Comment by Finb** [comment]
给你发邮件了~
