### ISSUE TITLE
又发现了一个问题，在话题详情里打开的链接，有些页面直接被Navigation给档住了

### ISSUE THREAD

**Issue by atjiu** [Finb/V2ex-Swift#55]
比如这个话题里的链接   https://www.v2ex.com/t/458229

![untitled](https://user-images.githubusercontent.com/6915570/40598920-235a6ad0-627d-11e8-9d55-f6032d5a2f3b.gif)

其它好像都正常，目前只发现了这一个链接，我估计应该是人家页面写的问题 : )

**Comment by Finb** [comment]
好像只有微信这个页面会这样
WKWebView 自动调整inset无效了，不知道具体为啥
