### ISSUE TITLE
大佬，用户中心的话题跟评论，能否做成TabLayout，左右切换，可以加载更多自己（别人）的话题和评论

### ISSUE THREAD

**Issue by atjiu** [Finb/V2ex-Swift#57]
类似这样的
![image](https://user-images.githubusercontent.com/6915570/40707855-79e0efde-6424-11e8-9edc-3894b133849d.png)

**Comment by atjiu** [comment]
惭愧呀，提了这么多issue，真想提pr，奈何我是swift小白，而且大佬app居然全是用代码实现的界面，storyboard空空如也，我啥时候要也能徒手写出来该多好，膜拜！

**Comment by Finb** [comment]
比较好的做法是这样~ 不过现在暂时停止更新只维护了，之后继续的时候改

现在storyboard也挺好的，当初我是学习Swift开发这个练手，就用了纯代码，我感觉都一样

issue pr 请随意😀

**Comment by atjiu** [comment]
大佬是通过什么方式学的呢？我在网上搜的教程大都是storyboard的方式开发的，求大佬学习经验^_^

**Comment by Finb** [comment]
不是大佬 - -
回想一下也没啥方式，Swift语言本身没啥好学的~ 
我是稍微看了下语法，然后新建这个项目就开始了，这个项目写的代码风格也没有很Swift~ 全是熟悉基本写法

刚接触iOS的话，先把UI开头的控件都用一遍，教程就 Xcode cmd + 鼠标左键 点进去看控件文档就行。再不行搜搜控件的教程，看看别人的用法，多写写就熟悉了，现在的UI开发还是挺简单的，常用控件也就那么些，顶多几天就学完了，之后就是练熟吧

如果你有兴趣可以加我QQ 273172722， 有时间可以QQ讨论，这里就不说了，跑题了 😀
