### ISSUE TITLE
登录功能实现的方法？

### ISSUE THREAD

**Issue by ForeverQ** [Finb/V2ex-Swift#6]
由于官方的 api 并不十分完善，想问下获取帖子 List 和登录这样的功能是用什么技术实现的？

**Comment by Finb** [comment]
登陆功能 是模拟请求
具体代码在这
https://github.com/Finb/V2ex-Swift/blob/master/Model/UserModel.swift
里面 Login 方法。

登陆请求需要三个参数， username 、password 和一个页面中的once字符串
将这三个参数 模拟成post请求发送给服务器。

如果登陆成功，服务器会返回主页（自己设置登陆成功后跳转的页面，我是设置跳转到主页)，
然后自己判断主页有没有一些登陆后特征，比如我是看有没有用户头像，如果有则证明登陆成功。

登陆成功时，服务器会写入cookie，这些cookie会自动被系统保存在default settings 中，下次请求时，这些cookie会自动的附加到请求里。服务器就知道我是登陆状态。

退出登陆只需要清空这些cookie即可

首页List 是使用第三方库 Ji 解析HTML 得到，具体请看
https://github.com/Finb/V2ex-Swift/blob/master/Model/TopicListModel.swift
里面的 getTopicList 方法

就是普通的解析HTML ，使用Ji提供的方法，里面用的是XPATH，一种很方便简单易懂的元素路径描述方法。

**Comment by ForeverQ** [comment]
好的。现在也在学习 Swift，写得很详细，非常非常感谢！
