### ISSUE TITLE
大大webview里如果有自动播放音乐的话，就算返回到详情页面还是会继续唱歌。

### ISSUE THREAD

**Issue by atjiu** [Finb/V2ex-Swift#66]
https://www.v2ex.com/t/484971 
这个帖子里面的博客链接打开之后，会自动唱歌，然后返回到详情页，还是会唱，再打开一个其他的帖子里面的链接，后台音乐还是不停，除非把app强退了，音乐才会停止。

**Comment by Finb** [comment]
确实是，循环引用导致 WKWebView 没被释放。 - -
