### ISSUE TITLE
请问大佬，登陆是如何实现的

### ISSUE THREAD

**Issue by jelly-cai** [Finb/V2ex-Swift#68]

**Comment by Finb** [comment]
https://github.com/Finb/V2ex-Swift/blob/b8865a9368d31749a9ad2c427f386c06d2a7ddb1/Controller/LoginViewController.swift#L105

https://github.com/Finb/V2ex-Swift/blob/b8865a9368d31749a9ad2c427f386c06d2a7ddb1/Model/UserModel.swift#L60

只是模拟请求， 将参数组装好发到服务器。
登录成功后服务器会设置cookie，请求时带上这些cookie（这些都是网络请求库自动管理的）
大概就这个流程
