### ISSUE TITLE
大大，在分享的弹层里能否加个复制当前帖子链接的功能？

### ISSUE THREAD

**Issue by atjiu** [Finb/V2ex-Swift#69]
有时候分享到qq会失败，也不知道为啥，就只能用safari打开了，然后再复制链接，比较麻烦，所以如果能有个复制帖子链接的功能就好了

**Comment by Finb** [comment]
现在是有的，在分享界面，下面那一栏有个复制按钮

**Comment by atjiu** [comment]
@Finb 原来还要先点一下分享，决在意看 😂
