### ISSUE TITLE
可能是bug。

### ISSUE THREAD

**Issue by Abirdcfly** [Finb/V2ex-Swift#7]
不确定是不是bug。登陆后点击头像出来的还是登录界面。。

不过确实很好用！大赞！

**Comment by Finb** [comment]
谢谢反馈！

头像那块还没有头像相关的功能，先放个重登录的功能，不是bug喔，不过可能有点不合常规 ，之后慢慢完善后会去掉，

再次感谢！🙏
Abirdcfly <notifications@github.com>于2016年3月6日 周日01:15写道：

**Comment by Finb** [comment]
谢谢反馈！

头像那块还没有头像相关的功能，先放个重登录的功能，不是bug喔，不过可能有点不合常规 ，之后慢慢完善后会去掉，

再次感谢！🙏
