### ISSUE TITLE
大佬，系统主题切换回来后还有部分是暗的

### ISSUE THREAD

**Issue by atjiu** [Finb/V2ex-Swift#73]
感谢适配自动切换主题^_^

![B7821186-3E62-42A1-A2B2-82C00DADCCB9](https://user-images.githubusercontent.com/6915570/70398704-12520c80-1a59-11ea-8742-cf07c69ecbbc.png)

**Comment by Finb** [comment]
唔。。。这个页面没想到还挺麻烦的
暂时刷新下页面解决吧
