### ISSUE TITLE
访问v2ex官网提示连接被重置？发生了什么？？？

### ISSUE THREAD

**Issue by Droid-MAX** [Finb/V2ex-Swift#79]
20210221-21:42,LOC疑似遭遇GFWBUG攻击，其解析IP（23.225.155.85）被TCP咔嚓了，23.225.155.83的TCP还部分正常，23.225.155.84基本正常
连带CloudFlare的官网跟DNS也一起咔嚓掉了，部分地区仍能正常访问

https://www.hostloc.com/thread-809969-1-1.html

**Comment by Finb** [comment]
V2EX算境外网站，这也正常吧
