### ISSUE TITLE
MAC OS X EI Capitan 10.11 + XCode 7.2.1 编译错误

### ISSUE THREAD

**Issue by zhujinlong** [Finb/V2ex-Swift#9]
MAC OS X EI Capitan 10.11
XCode 7.2.1

clone完成后pod install成功，但编译出现

~/V2ex-Swift/Pods/YYText/YYText/Component/YYTextEffectWindow.h:16:9: 'YYtext/YYTextSelectionView.h' file not found

~/V2ex-Swift/View/TopicDetailCommentCell.swift:10:8: Could not build Objective-C module 'YYText'

是哪里少做了吗？

**Comment by Finb** [comment]
请尝试使用 V2ex-Swift.xcworkspace 打开项目，并且不需要 pod install。

**Comment by zhujinlong** [comment]
确实是使用V2ex-Swift.xcworkspace打开的，重新做了一次，没有做pod install，还是有同样问题，我再看看..

**Comment by Finb** [comment]
我的环境和你一致，应该是不会有编译问题的。
你再试试看吧，如果还有问题，可以加我qq 273172722
